### ISSUE TITLE
Reuse existing terminal window for additional tests

### ISSUE THREAD

**Issue by anrie** [klen/nvim-test#1]
Hey,

thanks for this handy plugin!

I noticed if I run a test (e.g. via `TestNearest`), change the test and run it again the new test session starts in a new, additional split window/terminal.

I think it would be cool if the existing terminal could be reused. Is this already possible? If not, I think it would be a nice addition.

Thanks,
Andreas

**Comment by anrie** [comment]
Okay, I realized that it's probably not that simple. `vim-test` for example delegates my desired behavior to [`harpoon`](https://github.com/vim-test/vim-test#strategies).

For now I simply chain the [`only`](http://vimdoc.sourceforge.net/htmldoc/windows.html#:on) command with `TestNearest` (`:on | TestNearest`) to prevent ending up with several splits.
A  builtin solution would of course still be nice.

**Comment by klen** [comment]
Currently `vim-test` supports [toggleterm](https://github.com/akinsho/toggleterm.nvim), you may set `term='toggleterm'` and get the behaviour. It's possible to add similar terminal plugins as well.

But for the latest version of `nvim-test` I've added `keep_one` option (by default is true) which makes the behavior.
