### ISSUE TITLE
Support for more languages

### ISSUE THREAD

**Issue by majjoha** [klen/nvim-test#10]
Thank you for a great project!

I've been eager to replace [vim-test](https://github.com/vim-test/vim-test) with a Lua-based alternative, and this one seems to do more or less exactly what I need. However, I am missing support for [RSpec](https://rspec.info) and [Hspec](https://hspec.github.io) among others.

What would it take for me (or somebody else) to add support for more languages? Where does one start?

**Comment by klen** [comment]
@majjoha Thank you for the feedback. To add more test runners please check any [runner's source code](https://github.com/klen/nvim-test/tree/main/lua/nvim-test/runners). You need to add a new runner, setup tests command, treesitter query (use TSPlayground to build the queries). It's not hard to implement.

I'm using mostly python and js/ts, so I don't know how to work with different test tools/languages.

**Comment by majjoha** [comment]
Thank you so much! This looks great, and I can confirm that it works perfectly with RSpec. I have not had a chance to test it with `stack` since my M1 MacBook Pro and `stack` don't seem to play well together. I think I need to look into an issue with `runhaskell` as it does not load the modules specified in the Haskell files, but I'll create a PR if anything needs to be updated in the plugin.
