### ISSUE TITLE
[Feature Request] Allow passing environment variables to the runner

### ISSUE THREAD

**Issue by dhruvmanila** [klen/nvim-test#7]
Some test runners can take configuration via environment variables as well. For example, `vusted` can take `VUSTED_NVIM` and `VUSTED_ARGS`.

We can pass those variables in the `cmd` field like so: 
```lua
{ cmd = "VUSTED_ARGS='--headless --clean' vusted" }
```

But I think it would be better to provide native support like so:
```lua
{
  env = {
    VUSTED_ARGS = '--headless --clean',
  },
  cmd = 'vusted',
}
```

Internally, the `env` field will be converted to `key=value` string pairs and prefixed to the `cmd` field.

This is just a thought, it's ok if rejected :)

**Comment by klen** [comment]
@dhruvmanila it's kinda easy to implement. Done for v0.6.0

**Comment by klen** [comment]
you may setup it for a test runner:
```lua
require('nvim-test.runners.vusted'):setup {
  env = { VUSTED_ARGS = "--headless --clean" }
}
```
